name: ClaudeNotifier
options:
  bundleIdPrefix: com.claude
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

targets:
  ClaudeNotifier:
    type: application
    platform: macOS
    sources:
      - path: ClaudeNotifier
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.claude.notifier
        PRODUCT_NAME: ClaudeNotifier
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
